name: libpatchfinder

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

jobs:
  macOS:
    env:
      PROCURSUS: /opt/procursus
      PATH: /opt/procursus/bin:/opt/procursus/libexec/gnubin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Update Xcode
      id: Update-Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1.0'
    - name: macOS Build
      id: macOS-Build
      run: |
        ${{ github.workspace }}/.github/workflows/mac-bootstrap.sh
        ${{ github.workspace }}/.github/workflows/mac-build.sh
        ${{ github.workspace }}/.github/workflows/mac-post.sh
    - name: macOS x86_64 RELEASE Archive
      id: macOS-x86_64-RELEASE-Archive
      uses: actions/upload-artifact@v2
      with:
        name: libpatchfinder-macOS-x86_64-RELEASE
        path: |
          ${{ github.workspace }}/libpatchfinder-macOS-x86_64-*-RELEASE.tar.xz
    - name: macOS x86_64 DEBUG Archive
      id: macOS-x86_64-DEBUG-Archive
      uses: actions/upload-artifact@v2
      with:
        name: libpatchfinder-macOS-x86_64-DEBUG
        path: |
          ${{ github.workspace }}/libpatchfinder-macOS-x86_64-*-DEBUG.tar.xz
    - name: macOS arm64 RELEASE Archive
      id: macOS-arm64-RELEASE-Archive
      uses: actions/upload-artifact@v2
      with:
        name: libpatchfinder-macOS-arm64-RELEASE
        path: |
          ${{ github.workspace }}/libpatchfinder-macOS-arm64-*-RELEASE.tar.xz
    - name: macOS arm64 DEBUG Archive
      id: macOS-arm64-DEBUG-Archive
      uses: actions/upload-artifact@v2
      with:
        name: libpatchfinder-macOS-arm64-DEBUG
        path: |
          ${{ github.workspace }}/libpatchfinder-macOS-arm64-*-DEBUG.tar.xz
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Linux Build
        id: Linux
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster-slim
          options: -v ${{ github.workspace }}/..:/tmp/Builder/repos/
          run: |
            /tmp/Builder/repos/libpatchfinder/.github/workflows/linux-bootstrap.sh
            /tmp/Builder/repos/libpatchfinder/.github/workflows/linux-build.sh
            /tmp/Builder/repos/libpatchfinder/.github/workflows/linux-post.sh
      - name: Linux x86_64 RELEASE Build
        run: |
          mkdir -p /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/libpatchfinder/.github/workflows/name1.txt /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/libpatchfinder/.github/workflows/libpatchfinder1.tar.xz /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          mv /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/libpatchfinder1.tar.xz /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/$(cat /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/name1.txt)
      - name: Linux x86_64 DEBUG Build
        run: |
          mkdir -p /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/libpatchfinder/.github/workflows/name2.txt /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/libpatchfinder/.github/workflows/libpatchfinder2.tar.xz /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/
          mv /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/libpatchfinder2.tar.xz /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/$(cat /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/name2.txt)
      - name: libpatchfinder Linux x86_64 RELEASE Archive
        id: libpatchfinder-Linux-x86_64-RELEASE-Archive
        uses: actions/upload-artifact@v2
        with:
          name: libpatchfinder-Linux-x86_64-RELEASE
          path: |
            /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/libpatchfinder-Linux-x86_64*-RELEASE.tar.xz
      - name: libpatchfinder Linux x86_64 DEBUG Archive
        id: libpatchfinder-Linux-x86_64-DEBUG-Archive
        uses: actions/upload-artifact@v2
        with:
          name: libpatchfinder-Linux-x86_64-DEBUG
          path: |
            /home/runner/work/libpatchfinder/libpatchfinder/.github/workflows/libpatchfinder-Linux-x86_64*-DEBUG.tar.xz
